.MODEL SMALL
.STACK 64
.DATA
ARR DB 65H,56H,10H,30H,20H,60H,50H,20H,50H,60H
SUM DW ?
.CODE
MAIN PROC FAR
    MOV AX,@DATA
    MOV DS,AX
    LEA BX,ARR
    MOV CX,10       
    MOV AX,00H
    L1: ADD AL,[BX]
        JNC L2
        INC AH
    L2: INC BX
        LOOP L1
    MOV SUM,AX
    MOV AH,42H
    INT 21H
ENDP
END MAIN
