.MODEL SMALL
.DATA
STR DB "PROGRAMMING IS FUN $" 
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    MOV AH,09H
    LEA DX,STR
    INT 21H
    MOV AH,42H
    INT 21H         
ENDP
END MAIN